baseURL = 'https://ankurs2494.github.io/techVeda/'
languageCode = 'en-us'
title = 'My Tech Knowledge Notes'
theme = "PaperMod"
publishDir = "docs"

[params]
  author = "Ankur Singh"
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  defaultTheme = "auto"
  ShowPostMeta = false
  disableSpecial1stPost = true
  showDate = false
  showAuthor = false
  showReadingTime = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

# Networking topic
[[menu.main]]
name = "Networking"
url = "notes/networking/"
identifier = "networking"
weight = 10


# System Design topic
[[menu.main]]
name = "Architecture"
url = "notes/systemdesign/"
identifier = "systemdesign"
weight = 10


# Production use case
[[menu.main]]
name = "Operations"
url = "notes/operations/"
identifier = "operations"
weight = 10